export interface MachineryData {
    name: string;
    lifespanYears: number;
    lifespanHours: number | null;
    lifespanDays: number | null;
    residualValuePercentage: number;
}

export const MACHINERY_DATA: MachineryData[] = [
  { name: 'Abanador de cereal', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Adubadora autopropelida', lifespanYears: 10, lifespanHours: 12500, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Aplicador autopropelido', lifespanYears: 10, lifespanHours: 12500, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Atomizador costal motorizado', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Batedeira de cereais', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Beneficiadora', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Caminhão', lifespanYears: 10, lifespanHours: 12000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Capinadeira', lifespanYears: 10, lifespanHours: 6000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Carregadora agrícola de cana', lifespanYears: 10, lifespanHours: 15000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Colhedora', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Colhedora autopropelida miniceifa', lifespanYears: 10, lifespanHours: 6000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Cultivador motorizado p/ grãos e cereais', lifespanYears: 10, lifespanHours: 6000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Debulhadeira', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Desintegrador', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Ensiladeira', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Escavadeira hidráulica', lifespanYears: 10, lifespanHours: 24000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Forrageira autopropelida', lifespanYears: 10, lifespanHours: 15000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Micro trator', lifespanYears: 10, lifespanHours: 9000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Misturador autopropelido', lifespanYears: 10, lifespanHours: 15000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Motorroçadeira', lifespanYears: 10, lifespanHours: 6000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Motossegadeira', lifespanYears: 10, lifespanHours: 6000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Pá carregadeira', lifespanYears: 10, lifespanHours: 12000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Picador de forragem', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Picadora', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Plantadora automotriz', lifespanYears: 10, lifespanHours: 15000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Plantadora de cana picada e adubadora', lifespanYears: 15, lifespanHours: 1200, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Prensa enfardadeira algodão', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Pulverizador', lifespanYears: 10, lifespanHours: 10000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Pulverizador elétrico', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Raspadeira de mandioca', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Roçadeira manual', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Retroescavadeira', lifespanYears: 10, lifespanHours: 12000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Semeadeira adubadeira (pequeno trator)', lifespanYears: 15, lifespanHours: 1200, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Soprador', lifespanYears: 5, lifespanHours: 3600, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Transbordar para cana', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Trator de semente', lifespanYears: 5, lifespanHours: 9000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Trator', lifespanYears: 10, lifespanHours: 15000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Trator de esteira', lifespanYears: 10, lifespanHours: 15000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Trator de roda', lifespanYears: 10, lifespanHours: 15000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Trator de roda pequeno porte', lifespanYears: 10, lifespanHours: 6000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Triturador moedor e picador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Vagão', lifespanYears: 10, lifespanHours: 6000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Abastecedor de fertilizante', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 0 },
  { name: 'Abastecedor pulverizador', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Adubadeira manual', lifespanYears: 3, lifespanHours: 7200, lifespanDays: 300, residualValuePercentage: 0 },
  { name: 'Adubador mecânico', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Aração e descompactação', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Ancinho', lifespanYears: 5, lifespanHours: 3600, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Ancinho curvo', lifespanYears: 3, lifespanHours: 7200, lifespanDays: 300, residualValuePercentage: 0 },
  { name: 'Aplicador de inseticida', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Aplicador localizado de fertilizante', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Arado', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Arado (animal)', lifespanYears: 15, lifespanHours: 17520, lifespanDays: 730, residualValuePercentage: 0 },
  { name: 'Arrancador de soqueira', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Arrancador inverterdor (amendoim)', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Arrancadora de batata', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Atomizador acoplado', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Barra pulverizadora', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Bass Boy', lifespanYears: 5, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Batedeira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Bomba de irrigação', lifespanYears: 5, lifespanHours: 6750, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Caçamba carregadeira', lifespanYears: 12, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Canterador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Canudo abastecedor', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 0 },
  { name: 'Campânula para pomares', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Carreta graneleira, basculante, agrícola, di', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Carreta distribuidora de fertilizante, calcário', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Carreta pulverizadora', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Carreta sulcadora e distribuidora de torta d', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Carroceria', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Catadora de toco', lifespanYears: 20, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Ceifadeira de discos', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Cobrideira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Colhedora', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Coroadieira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Cortador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Cultivador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Cultivador (animal)', lifespanYears: 15, lifespanHours: 17520, lifespanDays: 730, residualValuePercentage: 0 },
  { name: 'Cultivador químico', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Cultivador subsolador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Cultivador sulcador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Debulhador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Decotadeira e recepadeira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Desenleirador de palha', lifespanYears: 5, lifespanHours: 3600, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Desensiladeira mescladora e alimentadora', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Desensiladora e distribuidor montado', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Desensiladora rebocada', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Desensilador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Desintegrador picador e moedor', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Destruidor de soqueira de algodão', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Distribuição de fertilizante químico, calcáric', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Distribuidor acoplado em caminhão', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Distribuidor de fertilizante orgânico', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Distribuidor e alimentador com batedor me', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Eliminador mecânico de soqueira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Empacotadeira automática', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Empilhadeira', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Embutidora de grãos para silo bolsa', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Encanteirador lateral', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Enleiradeira de grão de café', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Enxada rotativa', lifespanYears: 5, lifespanHours: 3600, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Enxada hexagonal', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Esgotadeira', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Espalhador de forragem', lifespanYears: 5, lifespanHours: 3600, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Espigadeira', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Esqueletadeira lateral', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Afofador de mandioca', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Garfo linha leve, pesada e econômica', lifespanYears: 3, lifespanHours: 7200, lifespanDays: 300, residualValuePercentage: 0 },
  { name: 'Grade aradora e niveladora, hidráulica, de', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Grade de disco triangular de aço (animal)', lifespanYears: 15, lifespanHours: 17520, lifespanDays: 730, residualValuePercentage: 0 },
  { name: 'Granuladeira', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Guincho', lifespanYears: 12, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Incorporador de fertilizante', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Lâmina enleiradora', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Manejo de solo e triturador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Miniempacotadeira automática', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Minienfardadeira', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Misturador de ração 1 e 2 eixos vertical ser', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Nivelador de solo cultivo mínimo', lifespanYears: 12, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Niveladora de solo grade plana', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Niveladora de solo (plaina hidráulica nivela', lifespanYears: 12, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Pá carregadeira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Picador desintegrador de restos de cultura', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Plaina', lifespanYears: 12, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Plantadora (mecânica)', lifespanYears: 15, lifespanHours: 1200, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Plantadora (animal)', lifespanYears: 15, lifespanHours: 17520, lifespanDays: 730, residualValuePercentage: 5 },
  { name: 'Plantadora (manual)', lifespanYears: 3, lifespanHours: 7200, lifespanDays: 300, residualValuePercentage: 0 },
  { name: 'Plataforma grãos', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Plataforma transportadora de hortaliças', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Podadeira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Prancha hidráulica', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Pulverizador', lifespanYears: 8, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Pulverizador costal', lifespanYears: 5, lifespanHours: 43800, lifespanDays: 1825, residualValuePercentage: 5 },
  { name: 'Raspadeira agrícola', lifespanYears: 20, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Rastelão', lifespanYears: 3, lifespanHours: 7200, lifespanDays: 300, residualValuePercentage: 0 },
  { name: 'Reboque', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Recolhedora', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Riscador de batata', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Roçadeira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Rolo destorroador compactador', lifespanYears: 10, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Rolo faca agrícola', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Rotavator', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Rotocanteirador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Segadora', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Semeadora adubadeira mecânica', lifespanYears: 15, lifespanHours: 1200, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Semeadora adubadeira manual', lifespanYears: 15, lifespanHours: 17520, lifespanDays: 730, residualValuePercentage: 5 },
  { name: 'Semeadora manual', lifespanYears: 3, lifespanHours: 7200, lifespanDays: 300, residualValuePercentage: 0 },
  { name: 'Soprador traseiro de café', lifespanYears: 5, lifespanHours: 3600, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Subsolador', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Subsolador adubador e cultivador para can', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Sulcador', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Sulcador adubador e cobridor', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Super plantadora de cana de terceiro ponto', lifespanYears: 15, lifespanHours: 1200, lifespanDays: null, residualValuePercentage: 20 },
  { name: 'Taipadeira', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Tanque roll on roll off', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Terraceador', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Transbordo agrícola', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Transcompletador', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Transmódulo para transporte', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Transportador', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Trilhadeira', lifespanYears: 10, lifespanHours: 2000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Triturador', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Vagão', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 25 },
  { name: 'Valeteadeira', lifespanYears: 15, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Varredeira arruadora', lifespanYears: 12, lifespanHours: 2500, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Veículo transbordo', lifespanYears: 15, lifespanHours: 5000, lifespanDays: null, residualValuePercentage: 5 },
  { name: 'Virador de feijão', lifespanYears: 5, lifespanHours: 3600, lifespanDays: null, residualValuePercentage: 5 },
];
